### ISSUE TITLE
Unable to use Asynchronous functions from 'fs'

### ISSUE THREAD

**Issue by Frixoe** [Frixoe/fot#7]
I have tried to use asynchronous functions but they perform unexpectedly and sometimes they just don't perform at all. I have looked at the documentation several times and know that I was using the correct syntax and params because I wasn't getting any errors.

Need someone to help me out with them.

**Comment by MarleyPlant** [comment]
I have had the same issues I am assuming it is due to the version of nodejs that we are using as I don't have these issues in TypeScript based projects

**Comment by Frixoe** [comment]
Alright, so it's node.
